### ISSUE TITLE
RPC Error in AddUI

### ISSUE THREAD

**Issue by Nicholaiii** [umods/AdminPanel#2]
Admins get kicked upon join, "RPC Error in AddUI" in log. Only plugins are Vanish and AdminPanel

**Comment by austinv900** [comment]
I'll look into it.

**Comment by lukespragg** [comment]
Pretty sure this is an issue with the image handling.

**Comment by Nicholaiii** [comment]
I wish I could be of more help but the console literally only says that. Is there a way for me to enable some debug information mode or w/e with a proper error stack?

**Comment by austinv900** [comment]
Unfortunately not since the error was thrown client side.

**Comment by lukespragg** [comment]
This error should be resolved in version 1.2.9.
